services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:7860" # Accessible depuis http://localhost:8000
    environment:
      PYTHONUNBUFFERED: "1"