from typing import Optional, Required
from pydantic import BaseModel, Field, model_validator


class ApplicationModel(BaseModel):
    SK_ID_CURR: Optional[float] = None
    app_CNT_CHILDREN: Optional[float] = None
    app_AMT_INCOME_TOTAL: float
    app_AMT_CREDIT: Optional[float] = None
    app_AMT_ANNUITY: Optional[float] = None
    app_AMT_GOODS_PRICE: Optional[float] = None
    app_REGION_POPULATION_RELATIVE: Optional[float] = None
    app_DAYS_BIRTH: Optional[float] = None
    app_DAYS_EMPLOYED: Optional[float] = None
    app_DAYS_REGISTRATION: Optional[float] = None
    app_DAYS_ID_PUBLISH: Optional[float] = None
    app_OWN_CAR_AGE: Optional[float] = None
    app_FLAG_MOBIL: Optional[float] = None
    app_FLAG_EMP_PHONE: Optional[float] = None
    app_FLAG_WORK_PHONE: Optional[float] = None
    app_FLAG_CONT_MOBILE: Optional[float] = None
    app_FLAG_PHONE: Optional[float] = None
    app_FLAG_EMAIL: Optional[float] = None
    app_CNT_FAM_MEMBERS: Optional[float] = None
    app_REGION_RATING_CLIENT: Optional[float] = None
    app_REGION_RATING_CLIENT_W_CITY: Optional[float] = None
    app_HOUR_APPR_PROCESS_START: Optional[float] = None
    app_REG_REGION_NOT_LIVE_REGION: Optional[float] = None
    app_REG_REGION_NOT_WORK_REGION: Optional[float] = None
    app_LIVE_REGION_NOT_WORK_REGION: Optional[float] = None
    app_REG_CITY_NOT_LIVE_CITY: Optional[float] = None
    app_REG_CITY_NOT_WORK_CITY: Optional[float] = None
    app_LIVE_CITY_NOT_WORK_CITY: Optional[float] = None
    app_EXT_SOURCE_1: Optional[float] = None
    app_EXT_SOURCE_2: Optional[float] = None
    app_EXT_SOURCE_3: Optional[float] = None
    app_APARTMENTS_AVG: Optional[float] = None
    app_BASEMENTAREA_AVG: Optional[float] = None
    app_YEARS_BEGINEXPLUATATION_AVG: Optional[float] = None
    app_YEARS_BUILD_AVG: Optional[float] = None
    app_COMMONAREA_AVG: Optional[float] = None
    app_ELEVATORS_AVG: Optional[float] = None
    app_ENTRANCES_AVG: Optional[float] = None
    app_FLOORSMAX_AVG: Optional[float] = None
    app_FLOORSMIN_AVG: Optional[float] = None
    app_LANDAREA_AVG: Optional[float] = None
    app_LIVINGAPARTMENTS_AVG: Optional[float] = None
    app_LIVINGAREA_AVG: Optional[float] = None
    app_NONLIVINGAPARTMENTS_AVG: Optional[float] = None
    app_NONLIVINGAREA_AVG: Optional[float] = None
    app_APARTMENTS_MODE: Optional[float] = None
    app_BASEMENTAREA_MODE: Optional[float] = None
    app_YEARS_BEGINEXPLUATATION_MODE: Optional[float] = None
    app_YEARS_BUILD_MODE: Optional[float] = None
    app_COMMONAREA_MODE: Optional[float] = None
    app_ELEVATORS_MODE: Optional[float] = None
    app_ENTRANCES_MODE: Optional[float] = None
    app_FLOORSMAX_MODE: Optional[float] = None
    app_FLOORSMIN_MODE: Optional[float] = None
    app_LANDAREA_MODE: Optional[float] = None
    app_LIVINGAPARTMENTS_MODE: Optional[float] = None
    app_LIVINGAREA_MODE: Optional[float] = None
    app_NONLIVINGAPARTMENTS_MODE: Optional[float] = None
    app_NONLIVINGAREA_MODE: Optional[float] = None
    app_APARTMENTS_MEDI: Optional[float] = None
    app_BASEMENTAREA_MEDI: Optional[float] = None
    app_YEARS_BEGINEXPLUATATION_MEDI: Optional[float] = None
    app_YEARS_BUILD_MEDI: Optional[float] = None
    app_COMMONAREA_MEDI: Optional[float] = None
    app_ELEVATORS_MEDI: Optional[float] = None
    app_ENTRANCES_MEDI: Optional[float] = None
    app_FLOORSMAX_MEDI: Optional[float] = None
    app_FLOORSMIN_MEDI: Optional[float] = None
    app_LANDAREA_MEDI: Optional[float] = None
    app_LIVINGAPARTMENTS_MEDI: Optional[float] = None
    app_LIVINGAREA_MEDI: Optional[float] = None
    app_NONLIVINGAPARTMENTS_MEDI: Optional[float] = None
    app_NONLIVINGAREA_MEDI: Optional[float] = None
    app_TOTALAREA_MODE: Optional[float] = None
    app_OBS_30_CNT_SOCIAL_CIRCLE: Optional[float] = None
    app_DEF_30_CNT_SOCIAL_CIRCLE: Optional[float] = None
    app_OBS_60_CNT_SOCIAL_CIRCLE: Optional[float] = None
    app_DEF_60_CNT_SOCIAL_CIRCLE: Optional[float] = None
    app_DAYS_LAST_PHONE_CHANGE: Optional[float] = None
    app_FLAG_DOCUMENT_2: Optional[float] = None
    app_FLAG_DOCUMENT_3: Optional[float] = None
    app_FLAG_DOCUMENT_4: Optional[float] = None
    app_FLAG_DOCUMENT_5: Optional[float] = None
    app_FLAG_DOCUMENT_6: Optional[float] = None
    app_FLAG_DOCUMENT_7: Optional[float] = None
    app_FLAG_DOCUMENT_8: Optional[float] = None
    app_FLAG_DOCUMENT_9: Optional[float] = None
    app_FLAG_DOCUMENT_10: Optional[float] = None
    app_FLAG_DOCUMENT_11: Optional[float] = None
    app_FLAG_DOCUMENT_12: Optional[float] = None
    app_FLAG_DOCUMENT_13: Optional[float] = None
    app_FLAG_DOCUMENT_14: Optional[float] = None
    app_FLAG_DOCUMENT_15: Optional[float] = None
    app_FLAG_DOCUMENT_16: Optional[float] = None
    app_FLAG_DOCUMENT_17: Optional[float] = None
    app_FLAG_DOCUMENT_18: Optional[float] = None
    app_FLAG_DOCUMENT_19: Optional[float] = None
    app_FLAG_DOCUMENT_20: Optional[float] = None
    app_FLAG_DOCUMENT_21: Optional[float] = None
    app_AMT_REQ_CREDIT_BUREAU_HOUR: Optional[float] = None
    app_AMT_REQ_CREDIT_BUREAU_DAY: Optional[float] = None
    app_AMT_REQ_CREDIT_BUREAU_WEEK: Optional[float] = None
    app_AMT_REQ_CREDIT_BUREAU_MON: Optional[float] = None
    app_AMT_REQ_CREDIT_BUREAU_QRT: Optional[float] = None
    app_AMT_REQ_CREDIT_BUREAU_YEAR: Optional[float] = None
    app_code_gender: Optional[float] = None
    app_own_car: Optional[float] = None
    app_own_realty: Optional[float] = None
    app_education_type: Optional[float] = None
    app_ratio_days_employed_vs_days_birth: Optional[float] = None
    app_ratio_income_vs_credit: Optional[float] = None
    app_ratio_income_total_vs_fam_number: Optional[float] = None
    app_ratio_annuity_vs_income_total: Optional[float] = None
    app_ratio_children_vs_family: Optional[float] = None
    app_age: Optional[float] = None
    app_NAME_CONTRACT_TYPE_Cash_loans: Optional[bool] = None
    app_NAME_CONTRACT_TYPE_Revolving_loans: Optional[bool] = None
    app_CODE_GENDER_F: Optional[bool] = None
    app_CODE_GENDER_M: Optional[bool] = None
    app_CODE_GENDER_XNA: Optional[bool] = None
    app_FLAG_OWN_CAR_N: Optional[bool] = None
    app_FLAG_OWN_CAR_Y: Optional[bool] = None
    app_FLAG_OWN_REALTY_N: Optional[bool] = None
    app_FLAG_OWN_REALTY_Y: Optional[bool] = None
    app_NAME_TYPE_SUITE_Children: Optional[bool] = None
    app_NAME_TYPE_SUITE_Family: Optional[bool] = None
    app_NAME_TYPE_SUITE_Group_of_people: Optional[bool] = None
    app_NAME_TYPE_SUITE_Other_A: Optional[bool] = None
    app_NAME_TYPE_SUITE_Other_B: Optional[bool] = None
    app_NAME_TYPE_SUITE_Spouse__partner: Optional[bool] = None
    app_NAME_TYPE_SUITE_Unaccompanied: Optional[bool] = None
    app_NAME_INCOME_TYPE_Businessman: Optional[bool] = None
    app_NAME_INCOME_TYPE_Commercial_associate: Optional[bool] = None
    app_NAME_INCOME_TYPE_Maternity_leave: Optional[bool] = None
    app_NAME_INCOME_TYPE_Pensioner: Optional[bool] = None
    app_NAME_INCOME_TYPE_State_servant: Optional[bool] = None
    app_NAME_INCOME_TYPE_Student: Optional[bool] = None
    app_NAME_INCOME_TYPE_Unemployed: Optional[bool] = None
    app_NAME_INCOME_TYPE_Working: Optional[bool] = None
    app_NAME_EDUCATION_TYPE_Academic_degree: Optional[bool] = None
    app_NAME_EDUCATION_TYPE_Higher_education: Optional[bool] = None
    app_NAME_EDUCATION_TYPE_Incomplete_higher: Optional[bool] = None
    app_NAME_EDUCATION_TYPE_Lower_secondary: Optional[bool] = None
    app_NAME_EDUCATION_TYPE_Secondary_secondary_special: Optional[bool] = Field(
        None, alias="app_NAME_EDUCATION_TYPE_Secondary_\\/_secondary_special"
    )
    app_NAME_FAMILY_STATUS_Civil_marriage: Optional[bool] = None
    app_NAME_FAMILY_STATUS_Married: Optional[bool] = None
    app_NAME_FAMILY_STATUS_Separated: Optional[bool] = None
    app_NAME_FAMILY_STATUS_Single_not_married: Optional[bool] = Field(
        None, alias="app_NAME_FAMILY_STATUS_Single_\\/_not_married"
    )
    app_NAME_FAMILY_STATUS_Unknown: Optional[bool] = None
    app_NAME_FAMILY_STATUS_Widow: Optional[bool] = None
    app_NAME_HOUSING_TYPE_Co_op_apartment: Optional[bool] = None
    app_NAME_HOUSING_TYPE_House_apartment: Optional[bool] = Field(
        None, alias="app_NAME_HOUSING_TYPE_House_\\/_apartment"
    )
    app_NAME_HOUSING_TYPE_Municipal_apartment: Optional[bool] = None
    app_NAME_HOUSING_TYPE_Office_apartment: Optional[bool] = None
    app_NAME_HOUSING_TYPE_Rented_apartment: Optional[bool] = None
    app_NAME_HOUSING_TYPE_With_parents: Optional[bool] = None
    app_OCCUPATION_TYPE_Accountants: Optional[bool] = None
    app_OCCUPATION_TYPE_Cleaning_staff: Optional[bool] = None
    app_OCCUPATION_TYPE_Cooking_staff: Optional[bool] = None
    app_OCCUPATION_TYPE_Core_staff: Optional[bool] = None
    app_OCCUPATION_TYPE_Drivers: Optional[bool] = None
    app_OCCUPATION_TYPE_HR_staff: Optional[bool] = None
    app_OCCUPATION_TYPE_High_skill_tech_staff: Optional[bool] = None
    app_OCCUPATION_TYPE_IT_staff: Optional[bool] = None
    app_OCCUPATION_TYPE_Laborers: Optional[bool] = None
    app_OCCUPATION_TYPE_Low_skill_Laborers: Optional[bool] = None
    app_OCCUPATION_TYPE_Managers: Optional[bool] = None
    app_OCCUPATION_TYPE_Medicine_staff: Optional[bool] = None
    app_OCCUPATION_TYPE_Private_service_staff: Optional[bool] = None
    app_OCCUPATION_TYPE_Realty_agents: Optional[bool] = None
    app_OCCUPATION_TYPE_Sales_staff: Optional[bool] = None
    app_OCCUPATION_TYPE_Secretaries: Optional[bool] = None
    app_OCCUPATION_TYPE_Security_staff: Optional[bool] = None
    app_OCCUPATION_TYPE_Waiters_barmen_staff: Optional[bool] = Field(
        None, alias="app_OCCUPATION_TYPE_Waiters\\/barmen_staff"
    )
    app_WEEKDAY_APPR_PROCESS_START_FRIDAY: Optional[bool] = None
    app_WEEKDAY_APPR_PROCESS_START_MONDAY: Optional[bool] = None
    app_WEEKDAY_APPR_PROCESS_START_SATURDAY: Optional[bool] = None
    app_WEEKDAY_APPR_PROCESS_START_SUNDAY: Optional[bool] = None
    app_WEEKDAY_APPR_PROCESS_START_THURSDAY: Optional[bool] = None
    app_WEEKDAY_APPR_PROCESS_START_TUESDAY: Optional[bool] = None
    app_WEEKDAY_APPR_PROCESS_START_WEDNESDAY: Optional[bool] = None
    app_ORGANIZATION_TYPE_Advertising: Optional[bool] = None
    app_ORGANIZATION_TYPE_Agriculture: Optional[bool] = None
    app_ORGANIZATION_TYPE_Bank: Optional[bool] = None
    app_ORGANIZATION_TYPE_Business_Entity_Type_1: Optional[bool] = None
    app_ORGANIZATION_TYPE_Business_Entity_Type_2: Optional[bool] = None
    app_ORGANIZATION_TYPE_Business_Entity_Type_3: Optional[bool] = None
    app_ORGANIZATION_TYPE_Cleaning: Optional[bool] = None
    app_ORGANIZATION_TYPE_Construction: Optional[bool] = None
    app_ORGANIZATION_TYPE_Culture: Optional[bool] = None
    app_ORGANIZATION_TYPE_Electricity: Optional[bool] = None
    app_ORGANIZATION_TYPE_Emergency: Optional[bool] = None
    app_ORGANIZATION_TYPE_Government: Optional[bool] = None
    app_ORGANIZATION_TYPE_Hotel: Optional[bool] = None
    app_ORGANIZATION_TYPE_Housing: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_1: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_10: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_11: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_12: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_13: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_2: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_3: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_4: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_5: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_6: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_7: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_8: Optional[bool] = None
    app_ORGANIZATION_TYPE_Industry__type_9: Optional[bool] = None
    app_ORGANIZATION_TYPE_Insurance: Optional[bool] = None
    app_ORGANIZATION_TYPE_Kindergarten: Optional[bool] = None
    app_ORGANIZATION_TYPE_Legal_Services: Optional[bool] = None
    app_ORGANIZATION_TYPE_Medicine: Optional[bool] = None
    app_ORGANIZATION_TYPE_Military: Optional[bool] = None
    app_ORGANIZATION_TYPE_Mobile: Optional[bool] = None
    app_ORGANIZATION_TYPE_Other: Optional[bool] = None
    app_ORGANIZATION_TYPE_Police: Optional[bool] = None
    app_ORGANIZATION_TYPE_Postal: Optional[bool] = None
    app_ORGANIZATION_TYPE_Realtor: Optional[bool] = None
    app_ORGANIZATION_TYPE_Religion: Optional[bool] = None
    app_ORGANIZATION_TYPE_Restaurant: Optional[bool] = None
    app_ORGANIZATION_TYPE_School: Optional[bool] = None
    app_ORGANIZATION_TYPE_Security: Optional[bool] = None
    app_ORGANIZATION_TYPE_Security_Ministries: Optional[bool] = None
    app_ORGANIZATION_TYPE_Self_employed: Optional[bool] = None
    app_ORGANIZATION_TYPE_Services: Optional[bool] = None
    app_ORGANIZATION_TYPE_Telecom: Optional[bool] = None
    app_ORGANIZATION_TYPE_Trade__type_1: Optional[bool] = None
    app_ORGANIZATION_TYPE_Trade__type_2: Optional[bool] = None
    app_ORGANIZATION_TYPE_Trade__type_3: Optional[bool] = None
    app_ORGANIZATION_TYPE_Trade__type_4: Optional[bool] = None
    app_ORGANIZATION_TYPE_Trade__type_5: Optional[bool] = None
    app_ORGANIZATION_TYPE_Trade__type_6: Optional[bool] = None
    app_ORGANIZATION_TYPE_Trade__type_7: Optional[bool] = None
    app_ORGANIZATION_TYPE_Transport__type_1: Optional[bool] = None
    app_ORGANIZATION_TYPE_Transport__type_2: Optional[bool] = None
    app_ORGANIZATION_TYPE_Transport__type_3: Optional[bool] = None
    app_ORGANIZATION_TYPE_Transport__type_4: Optional[bool] = None
    app_ORGANIZATION_TYPE_University: Optional[bool] = None
    app_ORGANIZATION_TYPE_XNA: Optional[bool] = None
    app_FONDKAPREMONT_MODE_not_specified: Optional[bool] = None
    app_FONDKAPREMONT_MODE_org_spec_account: Optional[bool] = None
    app_FONDKAPREMONT_MODE_reg_oper_account: Optional[bool] = None
    app_FONDKAPREMONT_MODE_reg_oper_spec_account: Optional[bool] = None
    app_HOUSETYPE_MODE_block_of_flats: Optional[bool] = None
    app_HOUSETYPE_MODE_specific_housing: Optional[bool] = None
    app_HOUSETYPE_MODE_terraced_house: Optional[bool] = None
    app_WALLSMATERIAL_MODE_Block: Optional[bool] = None
    app_WALLSMATERIAL_MODE_Mixed: Optional[bool] = None
    app_WALLSMATERIAL_MODE_Monolithic: Optional[bool] = None
    app_WALLSMATERIAL_MODE_Others: Optional[bool] = None
    app_WALLSMATERIAL_MODE_Panel: Optional[bool] = None
    app_WALLSMATERIAL_MODE_Stone__brick: Optional[bool] = None
    app_WALLSMATERIAL_MODE_Wooden: Optional[bool] = None
    app_EMERGENCYSTATE_MODE_No: Optional[bool] = None
    app_EMERGENCYSTATE_MODE_Yes: Optional[bool] = None
    SK_ID_BUREAU: Optional[float] = None
    bur_credit_active_closed: Optional[float] = None
    bur_credit_active_active: Optional[float] = None
    bur_credit_active_bad_debt: Optional[float] = None
    bur_amt_credit_sum: Optional[float] = None
    bur_amt_credit_sum_debt: Optional[float] = None
    bur_amt_credit_sum_overdue: Optional[float] = None
    bur_credit_day_overdue: Optional[float] = None
    bur_days_credit_min: Optional[float] = None
    bur_days_credit_max: Optional[float] = None
    bur_days_credit_mean: Optional[float] = None
    bur_amt_credit_active_active_sum: Optional[float] = None
    bur_amt_credit_active_closed_sum: Optional[float] = None
    bur_currency_1_sum: Optional[float] = None
    bur_currency_2_sum: Optional[float] = None
    bur_currency_3_sum: Optional[float] = None
    bur_currency_4_sum: Optional[float] = None
    bur_type_credit_type_another_type_of_loan: Optional[float] = None
    bur_type_credit_type_car_loan: Optional[float] = None
    bur_type_credit_type_cash_loan_non_earmarked: Optional[float] = Field(
        None, alias="bur_type_credit_type_cash_loan-non-earmarked"
    )
    bur_type_credit_type_consumer_credit: Optional[float] = None
    bur_type_credit_type_credit_card: Optional[float] = None
    bur_type_credit_type_interbank_credit: Optional[float] = None
    bur_type_credit_type_loan_for_business_development: Optional[float] = None
    bur_type_credit_type_loan_for_purchase_of_shares_margin_lending: (
        Optional[float]
    ) = None
    bur_type_credit_type_loan_for_the_purchase_of_equipment: Optional[float] = (
        None
    )
    bur_type_credit_type_loan_for_working_capital_replenishment: (
        Optional[float]
    ) = None
    bur_type_credit_type_microloan: Optional[float] = None
    bur_type_credit_type_mobile_operator_loan: Optional[float] = None
    bur_type_credit_type_mortgage: Optional[float] = None
    bur_type_credit_type_real_estate_loan: Optional[float] = None
    bur_type_credit_type_unknown_type_of_loan: Optional[float] = None
    bur_bal_max_status: Optional[float] = None
    bur_bal_nb_months_with_delay: Optional[float] = None
    cred_card_bal_total_balance_mean: Optional[float] = None
    cred_card_bal_total_credit_limit_mean: Optional[float] = None
    cred_card_bal_sk_dpd_sum: Optional[float] = None
    cred_card_bal_sk_dpd_def_sum: Optional[float] = None
    cred_card_bal_sk_dpd_max: Optional[float] = None
    cred_card_bal_sk_dpd_def_max: Optional[float] = None
    cred_card_bal_cnt_drawings_current_mean: Optional[float] = None
    cred_card_bal_cnt_drawings_atm_current_mean: Optional[float] = None
    cred_card_bal_credit_card_utilisation_ratio: Optional[float] = None
    cred_card_bal_credit_card_atm_ratio: Optional[float] = None
    cred_card_bal_credit_card_minimum_payment_ratio: Optional[float] = None
    cred_card_bal_type_name_contract_status_active: Optional[float] = None
    cred_card_bal_type_name_contract_status_approved: Optional[float] = None
    cred_card_bal_type_name_contract_status_completed: Optional[float] = None
    cred_card_bal_type_name_contract_status_demand: Optional[float] = None
    cred_card_bal_type_name_contract_status_refused: Optional[float] = None
    cred_card_bal_type_name_contract_status_sent_proposal: Optional[float] = None
    cred_card_bal_type_name_contract_status_signed: Optional[float] = None
    ins_pay_payment_count: Optional[float] = None
    ins_pay_amt_payment_sum: Optional[float] = None
    ins_pay_amt_instalment_mean: Optional[float] = None
    ins_pay_delta_payment_days_mean: Optional[float] = None
    ins_pay_total_fractional_payments: Optional[float] = None
    ins_pay_total_instalments: Optional[float] = None
    ins_pay_fractional_payment_ratio: Optional[float] = None
    prev_app_application_count: Optional[float] = None
    prev_app_delta_demanded_accepted_sum: Optional[float] = None
    prev_app_ratio_down_payment_mean: Optional[float] = None
    prev_app_days_decision_min: Optional[float] = None
    prev_app_nflag_insured_on_approval_mean: Optional[float] = None
    prev_app_amt_annuity_mean: Optional[float] = None
    prev_app_amt_annuity_min: Optional[float] = None
    prev_app_amt_annuity_max: Optional[float] = None
    prev_app_hour_process_mean: Optional[float] = None
    prev_app_hour_process_min: Optional[float] = None
    prev_app_hour_process_max: Optional[float] = None
    prev_app_rate_down_payment_mean: Optional[float] = None
    prev_app_rate_down_payment_min: Optional[float] = None
    prev_app_rate_down_payment_max: Optional[float] = None
    prev_app_amt_goods_price_mean: Optional[float] = None
    prev_app_amt_goods_price_min: Optional[float] = None
    prev_app_amt_goods_price_max: Optional[float] = None
    prev_app_amt_application_mean: Optional[float] = None
    prev_app_amt_application_min: Optional[float] = None
    prev_app_amt_application_max: Optional[float] = None
    prev_app_amt_credit_mean: Optional[float] = None
    prev_app_amt_credit_min: Optional[float] = None
    prev_app_amt_credit_max: Optional[float] = None
    prev_app_cnt_payment_mean: Optional[float] = None
    prev_app_cnt_payment_sum: Optional[float] = None
    prev_app_name_contract_status_approved: Optional[float] = None
    prev_app_name_contract_status_canceled: Optional[float] = None
    prev_app_name_contract_status_refused: Optional[float] = None
    prev_app_name_contract_status_unused_offer: Optional[float] = None
    prev_app_code_reject_reason_client: Optional[float] = None
    prev_app_code_reject_reason_hc: Optional[float] = None
    prev_app_code_reject_reason_limit: Optional[float] = None
    prev_app_code_reject_reason_sco: Optional[float] = None
    prev_app_code_reject_reason_scofr: Optional[float] = None
    prev_app_code_reject_reason_system: Optional[float] = None
    prev_app_code_reject_reason_verif: Optional[float] = None
    prev_app_code_reject_reason_xap: Optional[float] = None
    prev_app_code_reject_reason_xna: Optional[float] = None
    prev_app_weekday_appr_process_start_friday: Optional[float] = None
    prev_app_weekday_appr_process_start_monday: Optional[float] = None
    prev_app_weekday_appr_process_start_saturday: Optional[float] = None
    prev_app_weekday_appr_process_start_sunday: Optional[float] = None
    prev_app_weekday_appr_process_start_thursday: Optional[float] = None
    prev_app_weekday_appr_process_start_tuesday: Optional[float] = None
    prev_app_weekday_appr_process_start_wednesday: Optional[float] = None
    prev_app_ratio_refused_vs_total: Optional[float] = None
    prev_app_ratio_approved_vs_total: Optional[float] = None
    pos_cash_bal_total_days_past_due: Optional[float] = None
    pos_cash_bal_total_days_past_due_def: Optional[float] = None
    pos_cash_bal_total_months_with_dpd: Optional[float] = None
    pos_cash_bal_total_good_status: Optional[float] = None
    pos_cash_bal_total_bad_status: Optional[float] = None
    pos_cash_bal_max_term_extension: Optional[float] = None

    class Config:
        populate_by_name = True

    @model_validator(mode="before")
    @classmethod
    def unnest_pandas_json(cls, data: any) -> any:
        """Extrait automatiquement les valeurs de la structure imbriquée

        de type {"col": {"14343": val}} vers {"col": val}.
        """
        if isinstance(data, dict):
            flattened = {}
            for k, v in data.items():
                if isinstance(v, dict) and len(v) == 1:
                    flattened[k] = list(v.values())[0]
                else:
                    flattened[k] = v
            return flattened
        return data